/**
 * Utility to generate BBCode for a morgue record.
 */

export const generateMorgueBBCode = (record) => {
    if (!record) return '';

    const findingsTable = record.findings && record.findings.length > 0 
        ? `[table]
[tr]
[td][b]TIME[/b][/td]
[td][b]WOUND TYPE[/b][/td]
[td][b]BODY PART[/b][/td]
[td][b]DIST.[/b][/td]
[/tr]
${record.findings.map(f => `[tr]
[td]${f.time}[/td]
[td]${f.type}[/td]
[td]${f.part}[/td]
[td]${f.dist}[/td]
[/tr]`).join('\n')}
[/table]`
        : '[i]No findings recorded.[/i]';

    const adminNoteSection = record.adminNote 
        ? `[hr][/hr]
[b]ADMINISTRATIVE NOTES:[/b]
[quote]
${record.adminNote}
[/quote]` 
        : '';

    const bulletsText = record.bullets && record.bullets.length > 0
        ? record.bullets.map(b => `[*] Bullet recovered with striation marks - ${b.type} #${b.id}`).join('\n')
        : '[*] None';

    return `[divbox=white]
[center][size=150][b]MORGUE INTAKE RECORD[/b][/size]
[size=120][b]CASE #${record.caseId}[/b][/size][/center]

${adminNoteSection}

[hr][/hr]

[b]NAME:[/b] ${record.name}
[b]SEX:[/b] ${record.sex}
[b]IDENTIFIED:[/b] ${record.identified}
[b]LOCATION:[/b] ${record.location}
[b]TIME OF DEATH:[/b] ${record.timeOfDeath}
[b]CAUSE OF DEATH:[/b] ${record.causeOfDeath}

[hr][/hr]

[b]DNA PROFILE:[/b] 
[code]${record.dnaProfile}[/code]

[hr][/hr]

[b]PHYSICAL DESCRIPTION:[/b]
[quote]
${record.physicalDescription}
[b]Estimated age:[/b] ${record.estimatedAge}
[b]Tattoos description:[/b] ${record.tattoos}
[/quote]

[hr][/hr]

[b]FORENSIC DETAILS:[/b]
[list]
[*] [b]Blood alcohol concentration (BAC):[/b] ${record.bac}
[*] [b]Traces of narcotics:[/b] ${record.narcotics}
${bulletsText}
[/list]

[hr][/hr]

[b]AUTOPSY FINDINGS:[/b]
${findingsTable}

[hr][/hr]

[right][size=85][i]Generated by PHMC Forms Management System[/i][/size][/right]
[/divbox]`;
};
